name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    branches:
      - main
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            9.x
            8.x
            7.x
            6.x
            5.x

    - name: Restore dependencies
      run: dotnet restore src/ByteAether.Ulid.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release src/ByteAether.Ulid.sln

    - name: Run tests
      continue-on-error: true
      run: dotnet test --no-build --verbosity normal --logger "trx" --configuration Release src/ByteAether.Ulid.sln

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./**/TestResults/**/*.trx